version: '3'
services:
  webapp-1:
    image: cheftraining/webapp
    ports:
      - "8000:80"
      - "9631:9631"
  webapp-2:
    image: cheftraining/webapp
    command: --peer webapp-1
    links:
      - webapp-1
    ports:
      - "8001:80"
      - "9632:9631"
  lb-1:
    image: cheftraining/haproxy
    command: --peer webapp-2 --bind backend:webapp.default
    links:
      - webapp-2
    ports:
      - "8002:80"
      - "9633:9631"
